### ISSUE TITLE
create virtual environment

### ISSUE THREAD

**Issue by Alexyali** [Soheil-ab/DeepCC.v1.0#1]
hi author,
can i use `conda` to create a new virtual environment?
just like `conda create -n venv pyhton=3.6`
and what is the type of tensorflow? (2.0 or 1.x)  Thanks.

**Comment by Soheil-ab** [comment]
Hey @Alexyali ,

Yes, you can. As long as you install all required packages through conda, you are good to go. 
TensorFlow used in this project was TF 1.14.
