### ISSUE TITLE
Source Code for Modified Linux Kernel (including shim)

### ISSUE THREAD

**Issue by finleyb** [Soheil-ab/DeepCC.v1.0#4]
Hi, I see the repo includes the .deb binary files for the modified linux kernel (that includes the shim that interacts with TCP implementation), however is the source code for this modified linux kernel also available? Maybe I am just missing where this source code is located?  Thanks!

**Comment by Soheil-ab** [comment]
Hi @finleyb,

The exact source code for DeepCC is not ready for public release. However, you can find an updated version of the Kernel source code including Orca, DeepCC, and C2TCP [here](https://github.com/Soheil-ab/Orca/blob/master/linux/linux-4-13-1-orca-0521%2Bc2tcp.patch) .
