### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MohammedYahyaEAsiri** [Soheil-ab/DeepCC.v1.0#5]
Hi, @Soheil-ab

Thank you very much for your contribution to the community.

I am trying to run DeepCC ./evaluation and I am getting this error "attached". Which file used by the mm-thr script. I think I am missing something here.

Regards
![screenshot](https://user-images.githubusercontent.com/64312175/119605081-8641c980-be33-11eb-8485-f39013a2fb6c.jpeg)

**Comment by Soheil-ab** [comment]
Hey @MohammedYahyaEAsiri ,

The results/logs of experiments are supposed to be placed in _rl-module/log/_ path. So, you need to make a folder named **log** in the rl-module folder:  
      cd rl-module; mkdir -p log; 
I updated the build.sh script to reflect that need! 

Thanks
