### ISSUE TITLE
When I reproduced the paper, the result looked like this

### ISSUE THREAD

**Issue by wangxinyu1223** [Soheil-ab/DeepCC.v1.0#6]
pythongubuntu:-/Deepcc.v1.0-master/deepcc.v1.0$ ./evaluate.sh 8000 cubic
[sudo] python的密码:
rl-server:没有发现操作
rl-server-eval:没有发现操作
client:没有发现操作
python:没有发现操作
rt-server:没有发现操作
client:没有发现操作
python:没有发现操作
server:没有发现操作
cltent:没有发现操作
tcpdump:没有发现操作
rl-server:没有发现操作
python:没有发现操作
rL-server:没有发现操作
rl-server-eval: 没有发现操作
client:没有发现操作
python:没有发现操作
Running Deep-cubic: TMobile-LTE-driving. down
12735
[start-serverl starting RL Module (No Learning)....
logname:无登录名
sudo: /hone//venv/btn/python:找不到命令
Will be done in 474 seconds

**Do you have any idea what is wrong**

**Comment by Soheil-ab** [comment]
Hi @wangxinyu1223 ,
Am I supposed to know Chinese?! 
Assuming <没有发现操作> means "No operation found", it seems that you have not built/installed required applications/virtual-folder correctly.
Plz follow the README file to install the required things.

**Comment by shdjsh** [comment]
I also have this question, just like  
rl-server: no process found
rl-server-eval: no process found
client: no process found
python: no process found
rl-server: no process found
client: no process found
python: no process found
server: no process found
client: no process found
tcpdump: no process found
rl-server: no process found
python: no process found
rl-server: no process found
rl-server-eval: no process found
client: no process found
python: no process found
Running Deep-cubic: TMobile-LTE-driving.down
3316
[start_server] Starting RL Module (No learning) ...
logname: no login name
sudo: /home//venv/bin/python: command not found
Will be done in 474 seconds ...
mm-link: no process found
client: no process found
We got signal 15:
python: no process found
Experiment is finished.
Doing analysis ...
Done with analysis.    
and the file in  rl-module/log/results-deep-cubic*.tr is
deep-cubic-TMobile-LTE-driving.down-10-100-50-150-20-test
Can't open log/down-deep-cubic-TMobile-LTE-driving.down-10-100-50-150-20-test: No such file or directory at ./mm-thr line 41.
Must have at least one event at ./mm-thr line 149.
------------------------------
do you deal with it?  @wangxinyu1223 @Soheil-ab   can you help me with it?
