### ISSUE TITLE
encouter problem in installing patched Kernel

### ISSUE THREAD

**Issue by mollywu89** [Soheil-ab/DeepCC.v1.0#7]
I would like to reproduce the DeepCC, but I encouter crash after installing patched Kernel as README described. I have tried twice, the Linux throwed crash and failed to start up each time.I need to reinstall the ubuntu to recover from this error.
![current kernel version](https://user-images.githubusercontent.com/7372608/210026810-138d2a01-15de-4920-904b-ba4b1ac6be19.png)
![install kernel](https://user-images.githubusercontent.com/7372608/210026813-00661dbd-2fb6-4514-be18-ba628828cf88.png)
the server throwed the following carsh and failed to start up.
![encouter crash](https://user-images.githubusercontent.com/7372608/210026824-0c439629-f718-43ab-bca0-56ac0789172a.png)
 how do I need to solve this problem? Thank you for your help！

**Comment by Soheil-ab** [comment]
Hi, 
Have you tried this patch: [linux-4.13.1-0521-learner](https://github.com/Soheil-ab/c2tcp/blob/master/linux-patch/linux-image-4.13.1-0521-learner_4.13.1-0521-learner-10.00.Custom_amd64.deb) ? 
You can find more info about this patch here: https://github.com/Soheil-ab/c2tcp

**Comment by mollywu89** [comment]
I tried this patch: [linux-4.13.1-0521-learner](https://github.com/Soheil-ab/c2tcp/blob/master/linux-patch/linux-image-4.13.1-0521-learner_4.13.1-0521-learner-10.00.Custom_amd64.deb) today，I follow README in https://github.com/Soheil-ab/c2tcp， but I encouter crash in startup after reboot. The crash stack is the same one.
![install kernal2](https://user-images.githubusercontent.com/7372608/210526913-ba65d2b0-7367-47df-bcdc-7253584456c1.png)
![encouter crash2](https://user-images.githubusercontent.com/7372608/210526932-7251277b-d0c6-4e68-926e-4bd0623d9d0b.JPG)

I would like to build kernel by myself following the decripition in https://github.com/Soheil-ab/C2TCP-IFIP/.
Thanks a lot  for your help!

**Comment by Soheil-ab** [comment]
Yeah, compiling the code on your machine is a good way forward (the source code can be found on the rep). Most likely some drivers for your system were not activated during building these Kernels.
So remember to use your current working system's config file (/boot/config-`uname -r` ) during the compilation.
